[package]
name = "fff"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
polars = { version = "0.41.0", features = ["parquet", "sql", "lazy"] }
anyhow = "1.0.86"
itertools = "0.13.0"
clap = { version = "4.5.15", features = ["derive"] }
